apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-disease-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heart-disease-api
  template:
    metadata:
      labels:
        app: heart-disease-api
    spec:
      containers:
      - name: heart-disease-api
        image: 112875909909.dkr.ecr.ap-south-1.amazonaws.com/heart-disease-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
