apiVersion: v1
kind: Service
metadata:
  name: heart-disease-service
spec:
  type: LoadBalancer
  selector:
    app: heart-disease-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
