{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  endpoints:
    - port: http
      path: {{ .Values.prometheus.path }}
      interval: {{ .Values.prometheus.interval }}
      scrapeTimeout: {{ .Values.prometheus.scrapeTimeout }}
  namespaceSelector:
    matchNames:
      - default
{{- end }}
